language: node_js

node_js:
  - "4.2"
  - "0.12.0"

branches:
  only:
    - master
    - dev

install:
  - npm i jade
  - npm i babel@5.8
  - npm i babel-core@5.8
  - npm i coffee-script
  - npm i livescript
  - npm i typescript-simple
  - npm i stylus
  - npm i nib
  - npm i node-sass
  - npm i less
  - npm i postcss autoprefixer
  - npm i

after_success: make send-coverage

notifications:
  email: false

sudo: false
