language: node_js
node_js:
   - "0.12.0"

branches:
  only:
    - master
    - dev

before_install:
  npm install coffee-script && npm install babel-core && npm install livescript && npm install typescript-simple && npm install jade && npm install stylus && npm install nib && npm install

after_success:
  make test-coveralls

notifications:
    email: false
